---
name: on pull_request

"on":
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  show-event:
    name: Show GitHub Actions event
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=reopened#pull_request
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request
      - uses: actions/github-script@v7
        with:
          script: |
            console.info("github.event", context.payload)
  lint-gha:
    uses: ./.github/workflows/wf-lint-gha.yml
    secrets: inherit
