---
name: on pull_request

"on":
  pull_request:

jobs:
  show-event:
    name: Show GitHub Actions event
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 1
    runs-on: ubuntu-24.04
    steps:
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=reopened#pull_request
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea  # v7.0.1
        with:
          script: |
            console.info("github.event", context.payload)
  lint-gha:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/wf-lint-gha.yml
    secrets: inherit
