---
name: on pull_request

"on":
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  show-event:
    name: Show GitHub Actions event
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=reopened#pull_request
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request
      - uses: actions/github-script@v7
        with:
          script: |
            console.info("keys of github.event", Object.keys(context.payload));
            for (let key of ["action", "after", "before", "number"]) {
              console.info(`github.event.${key}`, context.payload[key]);
            }
            console.info(
              "keys of github.event.pull_request",
              Object.keys(context.payload.pull_request),
            );
            for (let key of [
              "active_lock_reason",
              "additions",
              "author_association",
              "body",
              "changed_files",
              "closed_at",
              "comments",
              "commits",
              "created_at",
              "deletions",
              "draft",
              "id",
              "locked",
              "maintainer_can_modify",
              "merge_commit_sha",
              "mergeable",
              "mergeable_state",
              "merged",
              "merged_at",
              "node_id",
              "number",
              "rebaseable",
              "review_comments",
              "state",
              "title",
              "updated_at",
            ]) {
              console.info(
                `github.event.pull_request.${key}`,
                context.payload.pull_request[key],
              );
            }
  lint-gha:
    uses: ./.github/workflows/wf-lint-gha.yml
    secrets: inherit
