---
name: on workflow_run completed

"on":
  workflow_run:
    workflows:
      - on pull_request
    types:
      - completed

jobs:
  show-event:
    name: Show GitHub Actions event
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=completed#workflow_run
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            console.info("github.event", context.payload)
  observe-gha:
    uses: ./.github/workflows/wf-observe-gha.yml
    secrets: inherit
