---
name: on workflow_run completed

"on":
  workflow_run:
    workflows:
      - on pull_request
    types:
      - completed

jobs:
  observe-gha:
    uses: ./.github/workflows/wf-observe-gha.yml
    secrets: inherit
