---
name: on workflow_run completed

"on":
  workflow_run:
    workflows:
      - on pull_request
    types:
      - completed

jobs:
  show-event:
    name: Show GitHub Actions event
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/ja/webhooks/webhook-events-and-payloads?actionType=completed#workflow_run
      - uses: actions/github-script@v7
        with:
          script: |
            console.info("github.event", context.payload)
      - name: get the workflow filename
        id: get-the-workflow-filename
        uses: actions/github-script@v7
        with:
          script: |
            return /([^/]+)\.ya?ml$/.exec(context.payload.workflow_run.path)[1]
      - name: show the workflow filename
        run: echo "${{steps.get-the-workflow-filename.outputs.result}}"
  observe-gha:
    uses: ./.github/workflows/wf-observe-gha.yml
    secrets: inherit
