---
name: Lint GitHub Actions

"on":
  workflow_call:

jobs:
  lint-gha-reviewdog:
    name: lint-gha-reviewdog
    permissions:
      checks: write
      contents: read
      pull-requests: write
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ne-sachirou/lint-gha-reviewdog@21e9e3be880468f3fceff09b97e02094eb000a43 # v0.0.6
        with:
          fail_on_error: true
          github_token: ${{github.token}}

  yamllint:
    name: yamllint
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1.22.0
        with:
          fail_level: error
          github_token: ${{github.token}}
          reporter: github-pr-review
