---
name: Lint GitHub Actions

"on":
  workflow_call:

jobs:
  lint-gha:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-yamllint@v1
        with:
          fail_level: error
          reporter: github-pr-review
      - uses: reviewdog/action-actionlint@v1
        with:
          fail_level: error
          reporter: github-pr-review
