---
name: Lint GitHub Actions

"on":
  workflow_call:

jobs:
  lint-gha:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: reviewdog/action-yamllint@1b1b6df34e7b178d78d8432a68b4f5ddc95b1c7e
        with:
          fail_level: error
          reporter: github-pr-review
      - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281
        with:
          # fail_level: error
          fail_on_error: true
          reporter: github-pr-review
