---
name: Lint GitHub Actions

"on":
  workflow_call:

jobs:
  lint-gha-reviewdog:
    name: lint-gha-reviewdog
    permissions:
      checks: write
      contents: read
      pull-requests: write
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ne-sachirou/lint-gha-reviewdog@b2173b3f186f624398947e89fe1e6524787983d5 # v0.0.9
        with:
          fail_on_error: true
          github_token: ${{github.token}}

  yamllint:
    name: yamllint
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: reviewdog/action-yamllint@de68272fdca5f2a961fb309e0d2e13c2eb186d9e # v1.23.1
        with:
          fail_level: error
          github_token: ${{github.token}}
          reporter: github-pr-review
