---
name: Lint GitHub Actions

"on":
  workflow_call:

jobs:
  lint-gha:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0
        with:
          fail_level: error
          reporter: github-pr-review
      - uses: reviewdog/action-actionlint@664c8ef5435569dd2880e62d891ab3ecdf98dc60
        with:
          # fail_level: error
          fail_on_error: true
          reporter: github-pr-review
