---
name: Lint GitHub Actions

"on":
  workflow_call:

jobs:
  lint-gha:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0
        with:
          fail_level: error
          reporter: github-pr-review
      - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281
        with:
          # fail_level: error
          fail_on_error: true
          reporter: github-pr-review
