---
name: Observe GitHub Actions

"on":
  workflow_call:

jobs:
  otel-cicd-action:
    runs-on: ubuntu-latest
    steps:
      - uses: corentinmusard/otel-cicd-action@v1
        with:
          otelServiceName: ${{ env.GITHUB_REPOSITORY }}
          otlpEndpoint: https://otlp-vaxila.mackerelio.com/v1/traces
          otlpHeaders: Accept=*/*,Mackerel-Api-Key=${{ secrets.MACKEREL_APIKEY }}
          runId: ${{ github.event.workflow_run.id }}
